kafka:
  applicationId: 'kafka-interactive-queries-application'
  bootstrapServersConfig: 'localhost:9092'
  schemaRegistryUrlConfig: 'http://localhost:8081'
  
  topics:
    fundscommand: 'queuing.funds.command'
    fundsoutcome: 'queuing.funds.outcome'
    balancequery: 'queuing.balance.query'
    balanceoutcome: 'queuing.balance.outcome'
    balance: 'queuing.funds.balance'
    
  stateStores:
    balanceReadModel: 'balance-read-model-state'
